"""added trust_score column for users table

Revision ID: 2cd01cea5e16
Revises: 88b3b1a84334
Create Date: 2025-12-28 20:15:59.934499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cd01cea5e16'
down_revision: Union[str, Sequence[str], None] = '88b3b1a84334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS idx_prices_status')
    op.add_column('users', sa.Column('trust_score', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trust_score')
    op.create_index(op.f('idx_prices_status'), 'prices', ['status'], unique=False)
    # ### end Alembic commands ###
