"""feat: add version column to Product for optimistic locking

Revision ID: 2dde3d75e34d
Revises: 72f254ae7f51
Create Date: 2026-04-11 23:08:40.723752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dde3d75e34d'
down_revision: Union[str, Sequence[str], None] = '72f254ae7f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('version', sa.Integer(), nullable=True))

    op.execute("UPDATE products SET version = 1 WHERE version is NULL")

    op.alter_column('products', 'version', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'version')
    # ### end Alembic commands ###
