"""add_composite_indexes_for_performance

Revision ID: 32fdff5abd74
Revises: 2dde3d75e34d
Create Date: 2026-04-19 15:44:20.551730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32fdff5abd74'
down_revision: Union[str, Sequence[str], None] = '2dde3d75e34d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_product_status_created', 'prices', ['product_id', 'status', 'created_at'], unique=False)
    op.create_index('idx_user_product_name', 'products', ['user_id', 'name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS idx_user_product_name')
    op.execute('DROP INDEX IF EXISTS idx_product_status_created')
    # ### end Alembic commands ###
