"""adding source column to Price table

Revision ID: 72f254ae7f51
Revises: ffe7178b2596
Create Date: 2026-03-08 20:48:21.721212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f254ae7f51'
down_revision: Union[str, Sequence[str], None] = 'ffe7178b2596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('source', sa.String(length=20), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'source')
    # ### end Alembic commands ###
