"""add index to product_id and created_at for table prices

Revision ID: 7ec86d0843e1
Revises: 2cd01cea5e16
Create Date: 2026-01-16 22:23:23.199985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ec86d0843e1'
down_revision: Union[str, Sequence[str], None] = '2cd01cea5e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_prices_created_at'), 'prices', ['created_at'], unique=False)
    op.create_index(op.f('ix_prices_product_id'), 'prices', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS ix_prices_product_id')
    op.execute('DROP INDEX IF EXISTS ix_prices_created_at')
    # ### end Alembic commands ###
