"""added status column for price and product, change datatype of prices.price from float to Decimal

Revision ID: 88b3b1a84334
Revises: 52e49d31bf3e
Create Date: 2025-12-28 17:30:23.899459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88b3b1a84334'
down_revision: Union[str, Sequence[str], None] = '52e49d31bf3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('is_correction', sa.Boolean(), nullable=False))
    op.add_column('prices', sa.Column('corrected_price_id', sa.Integer(), nullable=True))
    op.add_column('prices', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    op.execute('DROP INDEX IF EXISTS idx_prices_product_time')
    op.create_foreign_key(None, 'prices', 'prices', ['corrected_price_id'], ['id'])
    op.add_column('products', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'status')
    op.drop_constraint(None, 'prices', type_='foreignkey')
    op.create_index(op.f('idx_prices_product_time'), 'prices', ['product_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_column('prices', 'status')
    op.drop_column('prices', 'corrected_price_id')
    op.drop_column('prices', 'is_correction')
    # ### end Alembic commands ###
