"""adding is_monitored column for table products

Revision ID: ffe7178b2596
Revises: 7ec86d0843e1
Create Date: 2026-03-01 16:45:47.071434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffe7178b2596'
down_revision: Union[str, Sequence[str], None] = '7ec86d0843e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_monitored', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_monitored')
    # ### end Alembic commands ###
